-- Market data is regenerated by `yarn db:seed`, so the fund rows are cleared
-- here to let the new NOT NULL attribute columns be added. Accounts are not
-- touched. Cascades to fund_allocations and fund_similarities.
DELETE FROM "funds";--> statement-breakpoint
CREATE TYPE "public"."position_direction" AS ENUM('increased', 'decreased');--> statement-breakpoint
CREATE TABLE "fund_monthly_stats" (
	"fund_code" varchar(8) NOT NULL,
	"month" date NOT NULL,
	"total_value" numeric(20, 2) NOT NULL,
	"investor_count" integer NOT NULL,
	"net_flow" numeric(20, 2) NOT NULL,
	CONSTRAINT "fund_monthly_stats_fund_code_month_pk" PRIMARY KEY("fund_code","month")
);
--> statement-breakpoint
CREATE TABLE "fund_positions" (
	"fund_code" varchar(8) NOT NULL,
	"ticker" varchar(10) NOT NULL,
	"period" date NOT NULL,
	"direction" "position_direction" NOT NULL,
	"weight" numeric(6, 2) NOT NULL,
	"change_points" numeric(6, 2) NOT NULL,
	"rank" smallint NOT NULL,
	CONSTRAINT "fund_positions_fund_code_ticker_period_pk" PRIMARY KEY("fund_code","ticker","period")
);
--> statement-breakpoint
CREATE TABLE "fund_prices" (
	"fund_code" varchar(8) NOT NULL,
	"date" date NOT NULL,
	"price" numeric(18, 6) NOT NULL,
	CONSTRAINT "fund_prices_fund_code_date_pk" PRIMARY KEY("fund_code","date")
);
--> statement-breakpoint
CREATE TABLE "symbols" (
	"ticker" varchar(10) PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"color" varchar(9)
);
--> statement-breakpoint
ALTER TABLE "funds" ADD COLUMN "management_fee" numeric(5, 3) NOT NULL;--> statement-breakpoint
ALTER TABLE "funds" ADD COLUMN "withholding_tax" numeric(5, 2) NOT NULL;--> statement-breakpoint
ALTER TABLE "funds" ADD COLUMN "buy_value_days" smallint NOT NULL;--> statement-breakpoint
ALTER TABLE "funds" ADD COLUMN "sell_value_days" smallint NOT NULL;--> statement-breakpoint
ALTER TABLE "funds" ADD COLUMN "on_tefas" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "fund_monthly_stats" ADD CONSTRAINT "fund_monthly_stats_fund_code_funds_code_fk" FOREIGN KEY ("fund_code") REFERENCES "public"."funds"("code") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fund_positions" ADD CONSTRAINT "fund_positions_fund_code_funds_code_fk" FOREIGN KEY ("fund_code") REFERENCES "public"."funds"("code") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fund_positions" ADD CONSTRAINT "fund_positions_ticker_symbols_ticker_fk" FOREIGN KEY ("ticker") REFERENCES "public"."symbols"("ticker") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fund_prices" ADD CONSTRAINT "fund_prices_fund_code_funds_code_fk" FOREIGN KEY ("fund_code") REFERENCES "public"."funds"("code") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "fund_positions_lookup_idx" ON "fund_positions" USING btree ("fund_code","period","direction");--> statement-breakpoint
ALTER TABLE "funds" ADD CONSTRAINT "funds_founder_founders_name_fk" FOREIGN KEY ("founder") REFERENCES "public"."founders"("name") ON DELETE no action ON UPDATE no action;